### ISSUE TITLE
panic: character set not supported

### ISSUE THREAD

**Issue by fglaeser** [mylxsw/redis-gli#2]
![image](https://user-images.githubusercontent.com/30127016/56856424-552efc00-6930-11e9-904b-450e4d403f72.png)

**Comment by iminto** [comment]
Because tcell library which redis-Tui depends on does not support cygwin/msys,so you can't run it in cmder,but you can run it on Win's built-in cmd.

因为这个项目用的一个依赖tcell不支持cygwin/msys，所以报错了，但是可以用在内置的 windows命令行中。
可以参考这个issue [https://github.com/junegunn/fzf/issues/734](https://github.com/junegunn/fzf/issues/734)

**Comment by fglaeser** [comment]
Thanks. It is working fine with powershell
